print("-------------------")
print("DeviceHack 0.1 launched")
print("-------------------")
import time
time.sleep(0.5)
username = input("Enter username to log in: ")
print("Username:", username)
time.sleep(1)
password = input("Enter your password: ")   
if username == oMy and password == scrtmnu:
    print("s")
    time.sleep(0.1)
    print("se")
    time.sleep(0.1)
    print("sec")
    time.sleep(0.1)
    print("secr")
    time.sleep(0.1)
    print("secre")
    time.sleep(0.1)
    print("secret")
    time.sleep(0.1)
    print("secret m")
    time.sleep(0.1)
    print("secret me")
    time.sleep(0.1)
    print("secret men")
    time.sleep(0.1)
    print("secret menu")
    time.sleep(0.1)
    print("secret menu!")
    time.sleep(0.1)
    print("SeCrEt MeNu!")
    time.sleep(0.1)
    print("sEcReT mEnU!")
    time.sleep(0.1)
    print("SeCrEt MeNu!")
    time.sleep(0.1)
    print("sEcReT mEnU!")
    time.sleep(0.1)
    print("SeCrEt MeNu!")
    time.sleep(0.1)
    print("sEcReT mEnU!")
    time.sleep(1)
    print("welcome to the secret menu!. there is nothing here for now.")
    choice = input("say something to exit.")
else:
    time.sleep(0.3)
print("Succesfully logged in to the account", username)
time.sleep(0.3)
print("Entering operating system...")
time.sleep(0.5)
print("Entered...")
time.sleep(0.3)
print("Injecting DeviceHack...")
time.sleep(1.5)
print("Process failed.")
time.sleep(0.2)
print("Attempt secondary route?")
time.sleep(0.3)
print("Username:", username)
passwordcrack = input("Enter password to continue: ")
if passwordcrack == password:
    print("Attempting secondary route...")
    time.sleep(1)
    print("Entering internal software...")
    time.sleep(1)
    print("Success!")
    time.sleep(0.3)
    print("Brute forcing into device...")
    time.sleep(0.7)
    print("Success!")
    time.sleep(0.5)
    print("You can now minimize this window.")
    print("-----------------------------------")
    print("Thank you for using DeviceHack 0.1!")
    print("-----------------------------------")
else:
    print("Incorrect password. Stopping DeviceHack.")
    time.sleep(0.3)
    print("er3937659375omyg32exit0")
    time.sleep(0.3)
    print("er3937659375omyg32exit0")
    time.sleep(0.3)
    print("er3937659375omyg32exit0")
    time.sleep(0.3)
    print("er3937659375omyg32exit0")
    time.sleep(0.3)
    print("er3937659375omyg32exit0")
    print("Device Hack Ended")
    exit()