import time
def scrtmnufunc():
    print("s")
    time.sleep(0.1)
    print("se")
    time.sleep(0.1)
    print("sec")
    time.sleep(0.1)
    print("secr")
    time.sleep(0.1)
    print("secre")
    time.sleep(0.1)
    print("secret")
    time.sleep(0.1)
    print("secret m")
    time.sleep(0.1)
    print("secret me")
    time.sleep(0.1)
    print("secret men")
    time.sleep(0.1)
    print("secret menu")
    time.sleep(0.1)
    print("secret menu!")
    time.sleep(0.1)
    print("SeCrEt MeNu!")
    time.sleep(0.1)
    print("sEcReT mEnU!")
    time.sleep(0.1)
    print("SeCrEt MeNu!")
    time.sleep(0.1)
    print("sEcReT mEnU!")
    time.sleep(0.1)
    print("SeCrEt MeNu!")
    time.sleep(0.1)
    print("sEcReT mEnU!")
    time.sleep(1)
    print("welcome to the secret menu!. there is nothing here for now.")
    choice = input("say something to exit.")
